package bd.monumentor.repository.entities.localization;

public enum VoivodeshipEnum {

  DOLNOSLASKIE,
  KUJAWSKO_POMORSKIE,
  LUBELSKIE,
  LUBUSKIE,
  LODZKIE,
  MALOPOLSKIE,
  MAZOWIECKIE,
  OPOLSKIE,
  PODKARPACKIE,
  PODLASKIE,
  POMORSKIE,
  SLASKIE,
  SWIETOKRZYSKIE,
  WARMINSKO_MAZURSKIE,
  WIELKOPOLSKIE,
  ZACHODNIOPOMORSKIE

}
